# Generated by Django 5.0.2 on 2024-02-16 05:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("House_Price_model", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Get_Data_From_User_Model",
        ),
    ]
