# Generated by Django 5.0.2 on 2024-02-16 05:11

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("House_Price_model", "0004_delete_test"),
    ]

    operations = [
        migrations.CreateModel(
            name="test",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.FloatField()),
            ],
        ),
    ]
