# Generated by Django 5.0.2 on 2024-02-16 05:48

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("House_Price_model", "0006_delete_test"),
    ]

    operations = [
        migrations.CreateModel(
            name="Get_Data_From_User_Model",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=20)),
                ("area_type", models.CharField(max_length=20)),
                ("availability", models.CharField(max_length=20)),
                ("location", models.CharField(max_length=40)),
                ("size", models.CharField(max_length=20)),
                ("society", models.CharField(max_length=20)),
                ("total_sqft", models.FloatField()),
                ("bath", models.IntegerField()),
                ("balcony", models.IntegerField()),
            ],
        ),
    ]
