# Generated by Django 5.0.2 on 2024-02-23 05:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("House_Price_model", "0007_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="get_data_from_user_model",
            name="Date",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
