# Generated by Django 5.0.2 on 2024-02-23 06:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("House_Price_model", "0008_get_data_from_user_model_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="get_data_from_user_model",
            name="Date",
            field=models.DateField(default=datetime.date),
        ),
    ]
