# Generated by Django 5.0.2 on 2024-02-26 15:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("House_Price_model", "0009_alter_get_data_from_user_model_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="get_data_from_user_model",
            name="Date",
        ),
    ]
